# ov50 Linux/OSX build - courtesy to https://github.com/seandepagnier
language: cpp

matrix:
  include:
    - dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang

install:

    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
      then
        sudo apt-get -qq update;
        sudo apt-get install libwxgtk3.0-dev libwxgtk3.0-0 libgps-dev libglu1-mesa-dev libgtk2.0-dev libbz2-dev libtinyxml-dev;
        sudo apt-get install libexpat1-dev libcairo2-dev;
        sudo apt-get install rpm;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then
        brew install cairo libexif xz libarchive;
        wget http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz;
        tar xJf wx312_opencpn50_macos109.tar.xz -C /tmp;
        export PATH="/usr/local/opt/gettext/bin:$PATH";
        echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile;
        wget http://opencpn.navnux.org/build_deps/Packages.dmg;
        hdiutil attach Packages.dmg;
        sudo installer -pkg "/Volumes/Packages 1.2.5/Install Packages.pkg" -target "/";
      fi

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
       cmake -DCMAKE_BUILD_TYPE=Release ../ && make -sj2 package;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
        cmake -DwxWidgets_CONFIG_EXECUTABLE=/tmp/wx312_opencpn50_macos109/bin/wx-config -DwxWidgets_CONFIG_OPTIONS="--prefix=/tmp/wx312_opencpn50_macos109" -DCMAKE_INSTALL_PREFIX=/tmp/opencpn -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 .. && make -sj2 && make create-pkg;
     fi
  - ls -l;

notifications:
  email: false
git:
  depth: 10
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
deploy:
- provider: releases
  api_key:
      secure: "ZMJNkbf1QxwivytkWLiEZ5G4Q3WaXBTpFEwXe/GGgkA3qg/HNw7a0tSZAkLRIx/BohsrNIRRaCyETTpdv0pVcAByQmtenFVpChqzhdxln2QbIcZMJKRO/IsKnzj03zhJdIv/VQ+J56qVsIZGEL2AVl/zn5FHpKb7cYYpldJrSq7o5gb+N3EdhJ5Ksaw0r/TjYiWr7+M87T1ZBY5D+LzCGngYVTEG1XhPPLKzSd1w4JzRnyZ1IgVRh7dRmjzOhQyAOaRPUCr51Xh1eb6iHLq8d4uLHxHDscuiIHwqXhLEF/82ECtn9n6mbP3hxoCE/9CYcJsd2Z3r5hwgKoIqvMDyBJuiy8+j5WC5fcHq81OtRtFoYJSLLQlgjCtec3aOeuYfPkZCcw2HbF6udIdm3Xo5uLonIolMMq7YT7sh20INOOXVi0m+/9FBIXjPsfQDsX0FW0RfAWk4AJFnPARV3xKReNlQntuX4WORILeDCAmneob0jF7kP8W/u65mnTguic/2qsCVAeJRepfIon6i1+VmQO2n8b9S7XC6aHRN99Bi4uy5NePyl20Rqw8nCP/nn2SENgIQahPio+4vFX7B44hYdI87cFuKvvINOJxNup9IggQ4XYdVSCtD0u8sMfm4KT2O0NpPnYdqqB0V/KLfOhDm3UmmEqxEh86q/JPh3WCMyFc="
#"ZMJNkbf1QxwivytkWLiEZ5G4Q3WaXBTpFEwXe/GGgkA3qg/HNw7a0tSZAkLRIx/BohsrNIRRaCyETTpdv0pVcAByQmtenFVpChqzhdxln2QbIcZMJKRO/IsKnzj03zhJdIv/VQ+J56qVsIZGEL2AVl/zn5FHpKb7cYYpldJrSq7o5gb+N3EdhJ5Ksaw0r/TjYiWr7+M87T1ZBY5D+LzCGngYVTEG1XhPPLKzSd1w4JzRnyZ1IgVRh7dRmjzOhQyAOaRPUCr51Xh1eb6iHLq8d4uLHxHDscuiIHwqXhLEF/82ECtn9n6mbP3hxoCE/9CYcJsd2Z3r5hwgKoIqvMDyBJuiy8+j5WC5fcHq81OtRtFoYJSLLQlgjCtec3aOeuYfPkZCcw2HbF6udIdm3Xo5uLonIolMMq7YT7sh20INOOXVi0m+/9FBIXjPsfQDsX0FW0RfAWk4AJFnPARV3xKReNlQntuX4WORILeDCAmneob0jF7kP8W/u65mnTguic/2qsCVAeJRepfIon6i1+VmQO2n8b9S7XC6aHRN99Bi4uy5NePyl20Rqw8nCP/nn2SENgIQahPio+4vFX7B44hYdI87cFuKvvINOJxNup9IggQ4XYdVSCtD0u8sMfm4KT2O0NpPnYdqqB0V/KLfOhDm3UmmEqxEh86q/JPh3WCMyFc="
# canne    secure: "nx4vqgIxFQ/EWo1K8gUoKLpAOZEdlD5HRp+X2un7f61ydLpJ160JwrfojlzROnG+sZsbqdcEnGqqP+Kb0UeDPqZTdCJNPIvqruntJs9l3pfq2PxnWqdvaZapxNiBZfotyyF16p9qYQHPNgPqLqgiOzbCvEBRPp580lRUmHjDUsKPS9lCahfKNOm0bqc6KmOQCkk3CM8x8YLq7UFt1hCnb35jBNskTB+ePlMfUwShb2E7EMZR/X4BER/IVphV+ovW/SRI3fKVZOQBpednpOcDRFsRp5CQQaZPQ5SuQQwqrDTX6fgzE0zqSyhLaumjccBgydviId8u4wjlfe4KhfXmMZIUoOUiyib89XBkMVHqDQLF24fN3ibr3kVDYeggaxqXEKppw9Dx4nbXHf1qMn9hCqWxrnGIUFySMtbO/u8OGbhSsQ/qQlyvHnEbpk9NFtpOzj6LomRYqG1vlIMKGEm3eh0r6g4mae3ZhROZvP1lAeA8ZjhNftanywCL2GsXQCWDsbyUd2u5akvcGG4D25t4Bx/cj4Z80gtfGXuNEZFlywP3R0NPls9C5dpYOhV5Zqd5wyEmYLosXSbRnfylBY7gNSI9rxacrulfNInZvCc/o9Fr+vT7pdMgcEi65zIkT8B0nHhhqzFISsS98cIiEY+J/c9qf5yBrcULOm9R8X3SMzI="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/*.{deb,rpm,dmg,txz,pkg,pkg.tar.xz}"
  skip_cleanup: true
  on:
    repo: rgleason/tactics_pi
    tags: true
    all_branches: true